name: demo
on:
  push:
    branches:
      - 'main'

jobs:
  conditional_step:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v2
      with:
        # Checkout as many commits as needed for the diff
        fetch-depth: 2
    - shell: pwsh
      # Give an id to the step, so we can reference it later
      id: check_file_changed
      run: |

        $dirdiff = git diff --dirstat=files,0 HEAD~1  -- . ':!.github' | sed 's/^[ 0-9.]\+% //g'

        #echo  $dirdiff
        foreach($file in $dirdiff) {  #"@@ $file was changed" }     

        # Diff HEAD with the previous commit
        $diff = git diff --name-only HEAD^ HEAD

        $file = $file + 'a.json'
        $file1 = $file + 'b.json'
        
        # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
        $SourceDiff = $diff | Where-Object { $_ -match $file}
        $SourceDiff1 = $diff | Where-Object { $_ -match $file1}

        $HasDiff = $SourceDiff.Length -gt 0
        $HasDiff1 = $SourceDiff1.Length -gt 0

        Write-Host  $file + $HasDiff
        Write-Host  $file1 + $HasDiff1

        # Set the output named "docs_changed"
        Write-Host "::set-output name=docs_changed::$HasDiff" }

    # Run the step only with "docs_changed" equals "True"
    - shell: pwsh
      # steps.<step_id>.outputs.<output name>
      if: steps.check_file_changed.outputs.docs_changed == 'True'
      run: echo publish docs